In [7]:
import numpy as np

In [3]:
# 1. Creating Arrays
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
# 2. Array Operations
array_sum = array_1d + 10
print("Array Sum:", array_sum)

array_mult = array_2d * 2
print("Array Multiplication:\n", array_mult)


Array Sum: [11 12 13 14 15]
Array Multiplication:
 [[ 2  4  6]
 [ 8 10 12]]


In [5]:
# 3. Array Slicing
array_slice = array_2d[:, 1]
print("Array Slice:", array_slice)

Array Slice: [2 5]


In [6]:
# 4. Array Reshaping
array_reshaped = array_1d.reshape((5, 1))
print("Reshaped Array:\n", array_reshaped)

Reshaped Array:
 [[1]
 [2]
 [3]
 [4]
 [5]]
